server:
  port: ${SERVER_PORT:8081}

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.10.238}:${MYSQL_PORT:3306}/${MYSQL_DB:oss}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8